# Generated by Django 4.2.7 on 2023-11-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0003_orderitem_order_delivery_fee_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
    ]
