# Generated by Django 4.2.7 on 2023-11-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0005_alter_order_total_amount_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
