# Generated by Django 4.2.7 on 2023-11-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0008_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
