# Generated by Django 4.2.7 on 2023-11-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0009_order_total_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
