# Generated by Django 4.2.7 on 2023-11-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0010_alter_orderhistory_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount_paid',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
