# Generated by Django 4.2.7 on 2023-12-16 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0015_checkoutdetails_delete_checkoutinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
