# Generated by Django 4.2.7 on 2023-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0018_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='reference_number',
            field=models.UUIDField(unique=True),
        ),
    ]
