# Generated by Django 4.2.7 on 2023-12-28 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0019_alter_neworder_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='reference_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
