# Generated by Django 4.2.7 on 2023-12-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0020_alter_neworder_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
