# Generated by Django 4.2.7 on 2024-01-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0030_alter_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
