# Generated by Django 4.2.7 on 2024-02-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0032_purchase_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('order_item', models.ManyToManyField(related_name='order_history_items', to='sitepages.orderitem')),
            ],
        ),
    ]
