# Generated by Django 4.2.7 on 2024-02-01 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0033_orderhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
